# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MO_Playwrightdemo
#name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# âœ… ADD THIS LINE: Enables the "Run workflow" button in the GitHub UI
  workflow_dispatch:
    # No inputs needed for a basic manual run

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        #node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - run: npm run build --if-present

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright Tests    
      run: npx playwright test dropdown.spec.js;npx playwright test handleAlert.spec.js; npx playwright test google.spec.js
     

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    # - uses: actions/download-artifact@v4
    #     with:
    #       # Use the name the artifact was given when it was uploaded
    #       name: playwright-traces # Replace with the actual artifact name
    #       path: ./downloaded-traces 
          
    #   - name: Archive Downloaded Traces (Optional)
    #     run: tar -czf traces.tar.gz ./downloaded-traces
    #     # Now you can inspect the files on the runner or push them elsewhere

    # 1. UPLOAD HTML REPORT (For easy viewing on GitHub Summary)
    - uses: actions/upload-artifact@v4
      if: always() # Use 'always()' so the report uploads even if tests fail
      with:
        name: playwright-html-report
        path: playwright-report/
        retention-days: 30
        
    # 2. UPLOAD TRACES (Critical for debugging failure)
    # Assumes you configured 'trace: on-first-retry' or 'always' in playwright.config.js
    - uses: actions/upload-artifact@v4
      if: failure() # Only upload if the job failed to save space
      with:
        name: playwright-traces
        path: test-results/ # This is the default folder for trace files
        retention-days: 7